import { StyleSheet } from "react-native";
import Color from "../../../Constants/Color";


const styles = StyleSheet.create({
    backtext: {
        position: "absolute",
        left: 52,
        top: 59,
        width: 35,
        height: 21,
        fontStyle: "normal",
        fontFamily: "Poppins",
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 21,
        color: Color.primary,
    },
    backArrow: {
        position: "absolute",
        width: 17,
        height: 18,
        left: 29.92,
        top: 60.83,
    },
    skiptext: {
        position: "absolute",
        left: 335,
        top: 59,
        width: 30,
        height: 21,
        fontStyle: "normal",
        fontFamily: "Poppins",
        fontSize: 14,
        fontWeight: 500,
        lineHeight: 21,
        color: Color.primary,
    },
    no: {
        position: "absolute",
        width: 38,
        height: 21,
        left: 43,
        top: 103,
        fontFamily: "Poppins",
        fontWeight: 600,
        lineHeight: 21,
        fontSize: 14,
        fontStyle: "normal",
        color: Color.secondary,
        opacity: 0.5,
    },
    text: {
        position: 'absolute',
        width: 283,
        height: 36,
        left: 40,
        top: 132,
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: 600,
        fontSize: 24,
        lineHeight: 36,
        color: Color.secondary,
    },
    list: {
        position: "absolute",
        left: 35,
        top: 210,
        borderColor: "black",
        borderWidth: 1,
        width: 315,
        height: 73,
        padding: 10,
        borderRadius: 10,
    },
    heading: {
        width: 84,
        height: 21,
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: 500,
        fontSize: 14,
        lineHeight: 21,
        textAlign: "center",
        color: Color.secondary
    },
    data: {
        width: 200,
        height: 30,
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: 700,
        fontSize: 20,
        lineHeight: 30,
        textAlign: "center",
        color: Color.primary
    },
    checkbox: {
        position: "absolute",
        top: 25,
        left: 273,
    },
    list1: {
        position: "absolute",
        left: 35,
        top: 295,
        borderColor: "black",
        borderWidth: 1,
        width: 315,
        height: 73,
        padding: 10,
        borderRadius: 10,
    },
    list2: {
        position: "absolute",
        left: 35,
        top: 380,
        borderColor: "black",
        borderWidth: 1,
        width: 315,
        height: 73,
        padding: 10,
        borderRadius: 10,
    },
    data2: {
        width: 71,
        height: 30,
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: 700,
        fontSize: 20,
        lineHeight: 30,
        textAlign: "center",
        color: Color.primary
    },
    title: {
        marginVertical: 20,
        fontFamily: "Poppins",
        fontStyle: "normal",
        fontWeight: 500,
        fontSize: 18,
        lineHeight: 24,
        color: Color.secondary,


    },

    btn: {
        position: "absolute",
        width: 345,
        height: 50,
        left: 30,
        top: 722,
        backgroundColor: Color.primary,
        borderRadius: 10,
    },
    btntext: {
        color: Color.text,
        fontFamily: "Poppins",
        fontSize: 16,
        fontWeight: "600",
        fontStyle: "normal",
        lineHeight: 24,
        textAlign: "center",
        top: 10,
    }

})
export default styles;